name: CodeLab Chat Server - GraphQL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    name: CI from Repository
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Prepare checkout action
        uses: actions/checkout@v2.3.2

      - name: Prepare node action
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install node-modules
        run: npm install

  CD:
    needs: CI
    name: CD to Docker-Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Prepare checkout action
        uses: actions/checkout@v2.3.2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Variables
        run: echo '::set-env name=IMG_NAME::codeLab-chat-server'

      - name: Docker Image Build
        run: docker build -t $(IMG_NAME) .

      - name: Docker Image Tag
        run: |
          docker tag $(IMG_NAME) ${{ secrets.DOCKER_USER }}/$(IMG_NAME):${{ github.sha }}
          docker tag $(IMG_NAME) ${{ secrets.DOCKER_USER }}/$(IMG_NAME):latest

      - name: Docker Image push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/$(IMG_NAME):${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/$(IMG_NAME):latest
