name: Chat-App-Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  server-CI:
    name: GraphQL Server CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Prepare checkout action
        uses: actions/checkout@v2.3.2

      - name: Prepare node action
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install node-modules
        run: npm install

  server-CD:
    needs: server-CI
    name: GraphQL Server CD on docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - name: Prepare checkout action
        uses: actions/checkout@v2.3.2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t chat-app .

      - name: Docker Image Tag
        run: |
          docker tag chat-app ${{ secrets.DOCKER_USER }}/chat-app:${{ github.sha }}
          docker tag chat-app ${{ secrets.DOCKER_USER }}/back:latest

      - name: Docker Image push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/chat-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest
